services:
  find-app:
    image: ghcr.io/tardellirs/geo-deed-parser:latest
    container_name: find-app
    restart: unless-stopped
    environment:
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - GOOGLE_MAPS_SERVER_KEY=${GOOGLE_MAPS_SERVER_KEY}
    networks:
      - web

networks:
  web:
    external: true
